### ISSUE TITLE
Open all in new tabs not working

### ISSUE THREAD

**Issue by SMylk** [lucaseverett/toolbar-dial#41] opened 2023-03-17 13:32 UTC
When I right click on a folder and press "open all in new tabs" nothing happens same with "new window" options.

**Comment by lucaseverett** [comment] 2023-03-19 17:02
What is your browser/version and operating system?

Does it happen for all folders or only a specific one?

Will you please take a screenshot of any errors that appear in the browser console at the time you "open all in new tabs"?

I'm not able to reproduce this on any of my computers, and it's never been reported as an issue before, so I think it may be a specific bookmark that is causing this to happen for you.

**Comment by lucaseverett** [comment] 2023-03-22 01:30
Thank you for the additional information. I just updated Firefox and can now reproduce the issue as well. I'm going to do some research to determine what changed with the latest update so I can fix it.

**Comment by lucaseverett** [comment] 2023-03-25 14:16
Thank you for making me aware of this bug. The issue has been fixed in release 2.6.1.

Fixed by e8ce8aa.

**Closed by lucaseverett** 2023-03-25 14:17 UTC
Labels: bug
